ddjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ['url', 'username', 'email', 'is_staff']


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('index.urls')),
    path('login/', include('login.urls')),
    url(r'^', include(router.urls)),
    path(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path('', views.img),
    path('index1', views.xyz, name='login1'),
    path('file/', views.get_file),
    path('set_cookie/', views.set_cookie),
    path('get_cookie/', views.get_cookie),
    path('add_user', views.add_user),
    path('url_param/<id>', views.url_param, name="url_param"),
    path('request_param/', views.request_param, name="request_param"),
]

templates/bji.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<input id="butto" type="button" name="aaa" value="点我">
</body>
<script type="text/javascript" src="./static/jquery/jquery-3.2.1.min.js"></script>
<script>
    $("#butto").click(function () {
        var data = {"name": "tom", "age": 14};
        $.get('http://127.0.0.1:8000/index/file/', data, function (data, status) {
            console.log(status);
            console.log(data);
        })
    })
</script>
</html>

templates/bjiadd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<style>
    .inputW {
        width: 200px;
    }
</style>
<body>
<input class="inputW" id="usernameInput" type="text" placeholder="请输入用户名"/>
<input class="inputW" id="nameInput" type="text" placeholder="请输入名字"/>
<input class="inputW" id="pwdInput" type="text" placeholder="请输入密码"/>
<input class="inputW" id="emailInput" type="text" placeholder="请输入邮箱"/>
<input id="subButton" type="button" value="添加">
</body>
<script src="./static/jquery/jquery-3.2.1.min.js"></script>
<script>
    $("#subButton").click(function () {
        var data = {
            "username": $('#usernameInput').val(),
            "name": $('#nameInput').val(),
            "password": $('#pwdInput').val(),
            "email": $('#emailInput').val()
        };
        $.post('http://127.0.0.1:8000/index/add_user', data, function (data, status) {
            console.log(status);
            console.log(data);
        })
    })
</script>
</html>

templates/bjiuser.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/index/add_user" method="post">
    <label for="username">用户名：</label>
    <input id="username" name="username" placeholder="请输入用户名！">
    <!-- id-->
    <label for="password">密码：</label>
    <input id="password" name="password" placeholder="请输入密码！">
    <br>
    邮箱：<input id="email" name="email" placeholder="请输入邮箱！">
    姓名：<input id="name" name="name" placeholder="请输入姓名！">
    <br>
    <input type="submit">
</form>
<a href="/index">跳转1</a>
<a href="{% url 'index:login1' %}">跳转2</a>
<a href="{% url 'index:url_param' id="123" %}">url_param跳转</a>
<a href="{% url 'index:request_param' %}?username=sdf">url_param跳转</a>
{% load staticfiles %}
{#<img src="{% static 'index/a.jpg' %}">#}
{#<img src="{% static 'login/a.jpg' %}">#}

{% load my_filter %}
<p>{{ 5|mul:4 }}</p>
{% if user_list %}
    <table>
        {% for row in user_list reversed %}
            <tr>
                <td>{{ row.username }}</td>
                <td>{{ row.email }}</td>
                <td>{{ row.name }}</td>
                <td>{{ row.password }}</td>
                <td>|</td>
                <td>{{ forloop.counter }}</td>
                <td>{{ forloop.counter0 }}</td>
                <td>{{ forloop.recounter }}</td>
                <td>{{ forloop.recounter0 }}</td>
                <td>{{ forloop.first }}</td>
                <td>{{ forloop.last }}</td>
            </tr>
        {% endfor %}
    </table>
{% endif %}
{#<table>#}
{#    <tr>#}
{#        <td>{{ username }}</td>#}
{#        <td>{{ email }}</td>#}
{#        <td>{{ username }}</td>#}
{#        <td>{{ username }}</td>#}
{#    </tr>#}
{#</table>#}
</body>
</html>